#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/proc_fs.h>
#include <linux/seq_file.h>
#include <linux/utsname.h>
#include <linux/cpufreq.h>
#include <linux/cpumask.h>
#include <linux/mmzone.h>
#include <linux/vmstat.h>
#include <linux/time.h>
#include <linux/kernel_stat.h>
#include <linux/sysinfo.h>
#include <linux/processor.h>
#include <linux/mm.h>
#include <linux/swap.h>
#include <linux/mman.h>
#include <linux/timekeeping32.h>
#include <linux/slab.h>
#include <generated/utsrelease.h>
